version: '3.8'

services:
  trading-bot:
    image: your-docker-image  # Replace with your actual Docker image name
    container_name: trading_bot_container
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Store password in environment variable for security
      MYSQL_DB: trading
      API_KEY: ${API_KEY}  # Secure API keys via environment variables
      EXCHANGE_URL: ${EXCHANGE_URL}
    volumes:
      - ./src:/usr/src/app  # Mount source code for development
    ports:
      - "8000:8000"  # Expose the application port
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Store sensitive data securely
      MYSQL_DATABASE: trading
    ports:
      - "3306:3306"  # MySQL port exposure
    volumes:
      - db-data:/var/lib/mysql  # Persist MySQL data

  rl_agent_manager:
    build: .
    container_name: rl_agent_manager_container
    environment:
      API_KEY: ${API_KEY}  # Securely pass API key
      EXCHANGE_URL: ${EXCHANGE_URL}
    ports:
      - "8080:8080"  # Expose the agent manager service port
    deploy:
      replicas: 3  # Scale number of RL agent instances
      resources:
        limits:
          cpus: "1.0"  # CPU limit per instance
          memory: 1024M  # Memory limit per instance
    depends_on:
      - trading-bot

volumes:
  db-data:
