apiVersion: apps/v1
kind: Deployment
metadata:
  name: rl-agent-manager
spec:
  replicas: 5  # Number of agent instances
  selector:
    matchLabels:
      app: rl-agent-manager
  template:
    metadata:
      labels:
        app: rl-agent-manager
    spec:
      containers:
      - name: rl-agent
        image: your-docker-repo/rl-agent-manager:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: rl-agent-secrets
              key: API_KEY
        - name: EXCHANGE_URL
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: EXCHANGE_URL
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rl-agent-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: rl-agent-manager
